version: '2'
services:
  reverse-proxy:
    image: traefik
    #command: --api --docker
    ports:
      - "0.0.0.0:80:8080"
      - "0.0.0.0:8080:8080"
      - "0.0.0.0:443:8443"
    volumes:
      - $PWD/traefik.toml:/etc/traefik/traefik.toml
#      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - grav
      - default
  grav:
    image: tchabaud/grav
    ports:
      - "8000:80"
    networks:
      grav:
        aliases:
          - grav
    volumes:
      - $PWD:/var/www/grav-admin/user
networks:
  grav:
