title: 'Site web de l''association Koulenga'
default_lang: fr
author:
  name: 'Association Koulenga'
  email: koulenga@chabs.name
taxonomies:
  - category
  - tag
metadata:
  description: 'Grav is an easy to use, yet powerful, open source flat-file CMS'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog