title: 'Site web de l''association Koulenga'
default_lang: fr
author:
  name: 'Association Koulenga'
  email: koulenga@chabs.name
taxonomies:
  - category
  - tag
metadata:
  description: 'Site web de l''association Koulenga'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
redirects: null
routes: null
blog:
  route: /blog
