title: Grav
default_lang: fr
author:
  name: 'Association Koulenga'
  email: admin@koulenga.com
taxonomies:
  - category
  - tag
metadata:
  description: 'My Grav Site'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
redirects: null
routes: null
blog:
  route: /blog
